import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {Miniflare} from 'miniflare';
import {validateContent} from '../worker/validation.js';
let mf,db;
before(async()=>{mf=new Miniflare({modules:true,scriptPath:'dist/server/index.js',compatibilityDate:'2025-09-06',d1Databases:['DB'],bindings:{ADMIN_PASSWORD:'test-only-password',SCHOOL_CODE:'test-only-code'},serviceBindings:{ASSETS:()=>new Response('asset')}});db=await mf.getD1Database('DB');for(const file of (await fs.readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort()){for(const stmt of (await fs.readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint').filter(s=>s.trim()))await db.prepare(stmt).run();}});
after(async()=>{await mf?.dispose();});
function client(){return {cookie:'',csrf:'',async api(path,body){const response=await mf.dispatchFetch('https://game.test/api/'+path,{method:body===undefined?'GET':'POST',headers:{Cookie:this.cookie,'X-CSRF-Token':this.csrf,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(response.headers.get('set-cookie'))this.cookie=response.headers.get('set-cookie').split(';')[0];const text=await response.text();let data;try{data=JSON.parse(text);}catch{data=text;}if(data.csrf)this.csrf=data.csrf;return {status:response.status,data};}};}
async function login(sid){const c=client();assert.equal((await c.api('login',{password:'test-only-code'})).status,200);assert.equal((await c.api('select',{student_id:sid})).status,200);return c;}
async function correct(c,mid){const l=await c.api('learn',mid?{id:mid}:{});assert.equal(l.status,200);const q=await c.api('question',{id:l.data.id});assert.equal(q.status,200);const stored=await db.prepare('SELECT challenge FROM leases WHERE id=?').bind(l.data.id).first();const option=JSON.parse(stored.challenge).correct_id;return {l:l.data,q:q.data,option};}
test('149 ready records; 298 questions; stable canonical identifiers',async()=>{const c=await login('demo-1');const s=(await c.api('state')).data;assert.equal(s.total,149);assert.equal(Object.values(s.statuses).filter(v=>v==='ready').length,149);assert.deepEqual(validateContent(JSON.parse(await fs.readFile('data/content.json','utf8')),true).errors,[]);});
test('authentication, CSRF and answer secrecy',async()=>{const anon=client();assert.equal((await anon.api('roster')).status,401);const c=await login('demo-1');assert.equal((await c.api('admin/data')).status,403);const csrf=c.csrf;c.csrf='bad';assert.equal((await c.api('learn',{})).status,403);c.csrf=csrf;const x=await correct(c,'sukkah:1:1');assert.equal(x.q.options.length,4);assert.ok(!('correct_id' in x.q));assert.ok(!('questions' in x.l));await c.api('release',{id:x.l.id});});
test('simultaneous devices receive one lock; retry awards exactly one ticket',async()=>{const a=await login('demo-1'),b=await login('demo-2');const results=await Promise.all([a.api('learn',{id:'sukkah:1:2'}),b.api('learn',{id:'sukkah:1:2'})]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);const winner=results[0].status===200?a:b;const l=results.find(r=>r.status===200).data;await winner.api('question',{id:l.id});const option=JSON.parse((await db.prepare('SELECT challenge FROM leases WHERE id=?').bind(l.id).first()).challenge).correct_id;const answers=await Promise.all(Array.from({length:8},()=>winner.api('answer',{id:l.id,option})));assert.ok(answers.every(r=>r.status===200&&r.data.result==='correct'));assert.equal((await db.prepare("SELECT count(*) n FROM completions WHERE mishnah_id='sukkah:1:2'").first()).n,1);assert.equal((await db.prepare("SELECT count(*) n FROM tickets WHERE completion_id IS NOT NULL").first()).n,1);});
test('wrong answer persists cooldown across login and releases to another student',async()=>{const a=await login('demo-3'),x=await correct(a,'yoma:1:1');const wrong=x.q.options.find(o=>o.id!==x.option).id;const r=await a.api('answer',{id:x.l.id,option:wrong});assert.equal(r.data.result,'wrong');assert.ok(r.data.until>Date.now()/1000+290);const again=await login('demo-3');assert.equal((await again.api('learn',{id:'yoma:1:1'})).status,409);const b=await login('demo-4');const y=await correct(b,'yoma:1:1');assert.equal((await b.api('answer',{id:y.l.id,option:y.option})).data.result,'correct');});
test('expired lock can be taken; late answer gets friendly taken response',async()=>{const a=await login('demo-1'),x=await correct(a,'yoma:1:2');await db.prepare('UPDATE leases SET expires_at=1 WHERE id=?').bind(x.l.id).run();const b=await login('demo-2'),y=await correct(b,'yoma:1:2');assert.equal((await b.api('answer',{id:y.l.id,option:y.option})).data.result,'correct');assert.equal((await a.api('answer',{id:x.l.id,option:x.option})).data.result,'taken');});
test('imports validate errors and preserve game history; admin revocation atomic',async()=>{const a=client();await a.api('login',{role:'admin',password:'test-only-password'});const rows=JSON.parse(await fs.readFile('data/content.json','utf8'));const before=(await a.api('admin/data')).data;assert.ok(validateContent([rows[0],rows[0]]).errors.length);assert.ok(validateContent([{...rows[0],id:'bad'}]).errors.length);const bad=structuredClone(rows[0]);bad.questions[0].options.pop();assert.ok(validateContent([bad]).errors.length);bad.questions[0].options.push('not correct');bad.questions[0].correct='absent';assert.ok(validateContent([bad]).errors.length);const report=await a.api('admin/import',{kind:'content',rows,full:true,apply:true});assert.equal(report.data.applied,true);const after=(await a.api('admin/data')).data;assert.deepEqual(after.completions,before.completions);assert.deepEqual(after.tickets,before.tickets);const id=before.completions[0].id;const rs=await Promise.all([a.api('admin/revoke',{id}),a.api('admin/revoke',{id})]);assert.deepEqual(rs.map(r=>r.status).sort(),[200,400]);assert.equal((await db.prepare('SELECT COUNT(*) n FROM tickets WHERE reason=?').bind('ביטול השלמה '+id).first()).n,1);assert.equal((await a.api('admin/export?kind=raffle')).status,200);});
test('question positions vary across attempts',async()=>{const c=await login('demo-3'),positions=new Set();for(let i=0;i<16;i++){const x=await correct(c,'sukkah:2:1');positions.add(x.q.options.findIndex(o=>o.id===x.option));await c.api('release',{id:x.l.id});}assert.ok(positions.size>1);});
test('consistent full backup restores history exactly and invalidates sessions',async()=>{const a=client();await a.api('login',{role:'admin',password:'test-only-password'});const backup=(await a.api('admin/backup')).data;const old=backup.tables.tickets;await a.api('admin/ticket',{student_id:'demo-4',delta:1,reason:'temporary test'});assert.equal((await a.api('admin/restore',{backup,confirm:'שחזור'})).status,200);assert.equal((await a.api('admin/data')).status,401);await a.api('login',{role:'admin',password:'test-only-password'});assert.deepEqual((await a.api('admin/data')).data.tickets,old);});
test('final completion opens bonus without losing history; later rounds supported',async()=>{const c=await login('demo-3'),x=await correct(c,'yoma:8:9');const rows=await db.prepare('SELECT id FROM mishnayot WHERE id<>? AND id NOT IN(SELECT mishnah_id FROM completions WHERE round_id=1 AND revoked_at IS NULL)').bind(x.l.mishnah_id).all();for(const r of rows.results)await db.prepare("INSERT INTO completions(round_id,mishnah_id,student_id,class_id,completed_at,content_revision) VALUES(1,?,'demo-4','demo-b',unixepoch(),1)").bind(r.id).run();const result=await c.api('answer',{id:x.l.id,option:x.option});assert.equal(result.data.bonus_round,2);assert.equal((await db.prepare('SELECT COUNT(*) n FROM completions WHERE round_id=1 AND revoked_at IS NULL').first()).n,149);const state=(await c.api('state')).data;assert.equal(state.round.number,2);assert.equal(state.completed.length,0);const admin=client();await admin.api('login',{role:'admin',password:'test-only-password'});assert.equal((await admin.api('admin/round',{})).status,400);await db.prepare('UPDATE rounds SET finished_at=unixepoch() WHERE number=2').run();assert.equal((await admin.api('admin/round',{})).data.number,3);});
