PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS schema_versions(version INTEGER PRIMARY KEY, applied_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS tractates(id TEXT PRIMARY KEY,name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS chapters(tractate TEXT REFERENCES tractates(id),number INTEGER,PRIMARY KEY(tractate,number));
CREATE TABLE IF NOT EXISTS mishnayot(id TEXT PRIMARY KEY,tractate TEXT NOT NULL,chapter INTEGER NOT NULL,number INTEGER NOT NULL,FOREIGN KEY(tractate,chapter) REFERENCES chapters(tractate,number),UNIQUE(tractate,chapter,number));
CREATE TABLE IF NOT EXISTS content(mishnah_id TEXT PRIMARY KEY REFERENCES mishnayot(id),text TEXT NOT NULL DEFAULT '',questions TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'missing' CHECK(status IN('missing','ready','review')),revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS classes(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS students(id TEXT PRIMARY KEY,name TEXT NOT NULL,class_id TEXT NOT NULL REFERENCES classes(id),active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS rounds(id INTEGER PRIMARY KEY AUTOINCREMENT,number INTEGER NOT NULL UNIQUE,started_at INTEGER NOT NULL,finished_at INTEGER);
CREATE UNIQUE INDEX IF NOT EXISTS one_active_round ON rounds((1)) WHERE finished_at IS NULL;
CREATE TABLE IF NOT EXISTS completions(id INTEGER PRIMARY KEY AUTOINCREMENT,round_id INTEGER NOT NULL REFERENCES rounds(id),mishnah_id TEXT NOT NULL REFERENCES mishnayot(id),student_id TEXT NOT NULL REFERENCES students(id),class_id TEXT NOT NULL REFERENCES classes(id),completed_at INTEGER NOT NULL,revoked_at INTEGER,content_revision INTEGER NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS completed_once ON completions(round_id,mishnah_id) WHERE revoked_at IS NULL;
CREATE TABLE IF NOT EXISTS tickets(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id TEXT NOT NULL REFERENCES students(id),delta INTEGER NOT NULL CHECK(delta IN(-1,1)),completion_id INTEGER REFERENCES completions(id),reason TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS one_completion_ticket ON tickets(completion_id) WHERE completion_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS leases(id TEXT PRIMARY KEY,round_id INTEGER NOT NULL REFERENCES rounds(id),mishnah_id TEXT NOT NULL REFERENCES mishnayot(id),student_id TEXT NOT NULL REFERENCES students(id),expires_at INTEGER NOT NULL,content_revision INTEGER NOT NULL,text TEXT NOT NULL,questions TEXT NOT NULL,challenge TEXT,result TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS one_lease ON leases(round_id,mishnah_id) WHERE result IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS one_student_lease ON leases(student_id) WHERE result IS NULL;
CREATE TABLE IF NOT EXISTS cooldowns(student_id TEXT REFERENCES students(id),mishnah_id TEXT REFERENCES mishnayot(id),until_at INTEGER NOT NULL,PRIMARY KEY(student_id,mishnah_id));
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,student_id TEXT REFERENCES students(id),role TEXT NOT NULL CHECK(role IN('school','student','admin')),csrf TEXT NOT NULL,expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,at INTEGER NOT NULL,actor TEXT NOT NULL,action TEXT NOT NULL,details TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS login_limits(key TEXT PRIMARY KEY,attempts INTEGER NOT NULL,until_at INTEGER NOT NULL);
INSERT OR IGNORE INTO settings VALUES('cooldown_seconds','300');
INSERT OR IGNORE INTO settings VALUES('lease_seconds','600');
