import {build} from 'esbuild';
import fs from 'node:fs/promises';
await fs.rm('dist',{recursive:true,force:true});
await fs.mkdir('dist/client/static',{recursive:true});
await fs.cp('static','dist/client/static',{recursive:true});
await fs.copyFile('static/index.html','dist/client/index.html');
await build({entryPoints:['static/import-workbook.js'],outfile:'dist/client/static/import-workbook.bundle.js',bundle:true,format:'iife',minify:true});
await build({entryPoints:['worker/index.js'],outfile:'dist/server/index.js',bundle:true,format:'esm',platform:'neutral',target:'es2022',minify:true});
await fs.mkdir('dist/.openai',{recursive:true});
await fs.copyFile('.openai/hosting.json','dist/.openai/hosting.json');
await fs.cp('drizzle','dist/.openai/drizzle',{recursive:true});
console.log('Worker, static frontend and schema migrations built.');
